spring:
  application:
    name: vacation-dev

spring.jackson.default-property-inclusion: NON_NULL

server:
  port: 9100

#logging:
#  pretty-print: false
#
#management:
#  endpoints:
#    web:
#      base-path: "/management"
#      exposure:
#        include: "*"
#  server:
#    port: 9999